### ISSUE TITLE
Mejorar documentación y recortar imagenes

### ISSUE THREAD

**Issue by tonejito** [ChampionSean/CompilacionKernel#2]
Hola de nuevo

Una documentación que sólo consiste de imágenes no sirve de mucho. Es necesario que tu documentación explique lo que hiciste y no solo tenga las imágenes incrustadas.

Respecto a las imágenes, si no maximizaste la ventana cuando ejecutaste los comandos e imprimiste la pantalla, es necesario que recortes para que sólo se vea lo que quieres mostrar.

Puedes usar GIMP o algún editor de imágenes para hacer el recorte.

Saludos

**Comment by ChampionSean** [comment]
Hola, ya actualicé mi reporte de práctica.
Saludos.

El 7 de diciembre de 2017, 14:02, Andres Hernandez <notifications@github.com
